name: Apply

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read

on:
  push:

jobs:  
  s3-bucket-push:
    name: Github actions job to push to s3
    uses: akshay8181/central-repo/.github/workflows/main.yml@main
    with:
      BUCKET_NAME: dev
      AWS_REGION: "us-east-1"  
      
